### ISSUE TITLE
Add support for timeouts

### ISSUE THREAD

**Issue by bikeshedder** [najamelan/async_executors#3]
I'm currently looking for a way to perform runtime/executor angostic timeouts in the `deadpool` crate: bikeshedder/deadpool#68

I just found this crate and the following statement in the README:

```md
## Missing features

These are some features that aren't provided yet but that are on the todo list:

- an agnostic timeout mechanism.
- an agnostic interface for `spawn_blocking`.
```

If this crate supported `timeout` it would be a perfect fit for `deadpool`. :rocket:

What are the current plans on implementing this?

**Comment by najamelan** [comment]
The thing is timeouts are very tightly integrated into the reactors of the different frameworks and generally require extra deps and and extra thread. So far, async_executors have stayed away from spawning extra threads and dealing with reactors, providing a clean interface just to executors. 

I admit I haven't looked at the problem again recently. It would in some sense be a separate thing. That is going over the different providers of timers, look if a common interface can be derived that can be implemented by all of them and then design a trait. In itself that is completely orthogonal to what async_executors provides today. It sure would give a more wholesome package of tools for the user, but even then it might be worth implementing it in a different crate and re-exporting it behind a feature flag.

The spawn_blocking is very similar in that the `JoinHandle` type allows canceling a task when it yields, but blocking tasks don't yield, so I'm not sure it makes sense to use the same type (eg a type that pretends it can cancel).

On the more practical side, I rarely use timers, which is why I haven't done a more extensive analysis of the different implentations.

Do I get it right that you would like to use a timer in your library but leave it up to the user to decide the implementation, in the spirit of what async_executors does for executors? That would imply taking in a object like `impl Timer` from a caller? If so do you have a trait definition in mind that you feel would be the right interface? 

I could be motivated to work on that soon if it makes sense and there isn't some major obstacle (the research is actually the most work as often docs of different implementations aren't very clear about what goes on under the hood), but happy to think about the interface at least together.

**Comment by najamelan** [comment]
Ah, I remember the issue I think. tokio for example doesn't have a separate timer object. It is a feature you enable on the `Runtime`. That means it's probably hard to make it orthogonal to the executor. That's probably why I haven't gone forward on this so far.

**Comment by bikeshedder** [comment]
I did experiment with that a bit and found a way to implement this: https://github.com/bikeshedder/async-runtime

The implementation is really simple. Would you be interested in merging this? I could provide a PR for this feature.

For runtimes that don't support sleep it would need to return a `Err(TimeoutError::Unsupported)`.

**Comment by najamelan** [comment]
> I did experiment with that a bit and found a way to implement this: https://github.com/bikeshedder/async-runtime
> 
> The implementation is really simple. Would you be interested in merging this? I could provide a PR for this feature.

Thanks for prototyping that. It looks feasible indeed. I could accept a PR for that or I could have a stab at it myself. It's probably easier and faster for me to integrate it in a consistent manner in async_executors than for you as it's a quite involved feature. I would rather call the trait `Sleep` or `Timer` than `Runtime`, as `Runtime` has a connotation of packaging everything, and for now we have `Spawn` and `SpawnHandle` which allows users to specify clearly what they need. A function can take a parameter that says: `impl Spawn + Sleep` for example.

An open question is how to create some reasonable way to guarantee what is present for tokio? Right now I have added two builder types to guarantee the difference between single threaded and multithreaded executor at the type system level. If orthogonal features get included a different approach is needed, as I don't want the number of types to explode. Maybe it works just with a `sleep` feature which makes sure the timer is enabled when that feature is enabled and sets the right features on tokio. Im not sure if it's entire feasible, as tokio itself is feature gated, and I don't think that cargo allows us to express: "if tokio is enabled and sleep is enabled, also enable feature `rt-full` on tokio".

Maybe the best is to add the timeout method to an extension trait like `SleepExt`? That way we don't need to use a separate free standing function? I'm not sure actually, I would have to play around with it and write some code that uses it to see what is the nicest API. In any case if it were on an extension trait, `Sleep` would remain object safe, which is important.

Another thing I'm wondering about is whether it would be worth creating a `Sleep`/`Delay` future type instead of boxing. It probably is actually.

> For runtimes that don't support sleep it would need to return a `Err(TimeoutError::Unsupported)`.

I think executors that don't support sleep should either not implement the trait, or better just use futures-timer. This might also be complicated to express in cargo features. 

I'm looking forward to seeing this in action!

**Comment by najamelan** [comment]
@bikeshedder Did you want me to have a stab at this or are you still working on it?

**Comment by bikeshedder** [comment]
@najamelan I haven't looked into the implementation of `async_executors`, yet. I don't really get why it's split into various traits rather than having one big `Runtime` trait that contains all the methods that are expected to be part of the runtime implementation.

So it's probably best if you take care of this. Or you could tell me how you want it to be implemented and I'll can take a look...

**Comment by najamelan** [comment]
Ok, I will have a look at it over the next few days. Let's hope for success.

The reason it is split into several traits is to allow compile time checking of available features rather than having `Runtime` trait with certain methods that panic at runtime `unimplemented!()`. That is because there is a variety of use cases and implementations. There are executors that support spawning, but don't have an IO reactor (think wasm). It allows library code to specify exactly what it needs and the compiler will guarantee that this functionality is available.

There is also use for concurrency without the need for IO and timers, think an application that uses an actor model. It might not need IO.

Further, `SpawnHandle<T>` is generic over the output of the `JoinHandle<T>`. How would we express that on a `Runtime` trait? 

The disadvantage of the fine grained control is some boilerplate, but you can always create your own `Runtime` trait:
```rust
trait Runtime: Spawn + Sleep {}

impl<T> Runtime for T where: T: Spawn + Sleep {}
```
Now you can specify your function signatures as:
```rust
fn give_me_executor( exec: impl Runtime ) {}
```

This is much the same logic as why the standard library has `Debug` and `Display` rather than just having `Display` with a `debug` method.

**Comment by qiujiangkun** [comment]
I'm gonna implement it soon. However, implementing timeouts may be a breaking change, or we can leave old code untouched.

> An open question is how to create some reasonable way to guarantee what is present for tokio? Right now I have added two builder types to guarantee the difference between single threaded and multithreaded executor at the type system level. If orthogonal features get included a different approach is needed, as I don't want the number of types to explode. 

We can do something like it. Types wouldn't explode this way
```rust
trait TimerEnabled {}
trait TimerEnabledTrue {}
trait TimerEnabledFalse {}
trait IoEnabled {}
trait IoEnabledTrue {}
trait IoEnabledFalse {}
struct TokioCt<Timer: TimerEnabled, Io: IoEnabled> { ... }
#[async_trait]
impl<Io: IoEnabled> Sleep for TokioCt<TimerEnabledTrue, Io> {
    async fn sleep(&self) { tokio::time::sleep().await }
}
```

> Maybe it works just with a sleep feature which makes sure the timer is enabled when that feature is enabled and sets the right features on tokio. Im not sure if it's entire feasible, as tokio itself is feature gated, and I don't think that cargo allows us to express: "if tokio is enabled and sleep is enabled, also enable feature rt-full on tokio".

`tokio::time` has already been feature-gated 
```rust
cfg_time! {
    pub mod time;
}
```
We can make `TimerEnabledTrue` under a feature gate called `enable_tokio_timer`, so that users can only initilaize `TokioCt<TimerEnabledTrue, _>` with the `enable_tokio_timer` feature

> Another one is reactors. Maybe it makes sense to have a trait TokioIO, which guarantees that the reactor is enabled. And AsyncIO for the AsyncStd and AsyncGlobal executors, although I think for now async-std doesn't allow turning it off, I expect and hope they will in the future.

Same as my solution for Timers

> Maybe the best is to add the timeout method to an extension trait like SleepExt? That way we don't need to use a separate free standing function? I'm not sure actually, I would have to play around with it and write some code that uses it to see what is the nicest API. In any case if it were on an extension trait, Sleep would remain object safe, which is important.

> Another thing I'm wondering about is whether it would be worth creating a Sleep/Delay future type instead of boxing. It probably is actually.

See my [experiment](https://github.com/HappyCodingRust/async_executors/blob/e128b55468817aee79b07b48be9f900251566c7d/examples/glommio_ct_static.rs). I implemented a famaly of XxxStatic, which makes full use of compile time infomation. It's not hard to return a `impl Timer` for TimerStatic, where Timer is our trait.

When it comes to normal `Sleep`/`Timer`, I think Boxing is enough, unless you need finer control

**Problem**
My [YieldNowStatic::yield_now](https://github.com/HappyCodingRust/async_executors/blob/e128b55468817aee79b07b48be9f900251566c7d/src/yield_now.rs) cannot return a decent trait(maybe `trait YieldNowImpl` for all `Future<Output=()>`?), because `tokio::task::YieldNow` is private`

**Comment by bikeshedder** [comment]
For `deadpool` I finally opted against a 3rd party library and just added a small `enum` for selecting the runtime: https://github.com/bikeshedder/deadpool/blob/master/src/runtime.rs

The benefit with this implementation is that it doesn't need any heap allocations. The downside is of course that the code is now limited to the known runtimes and supporting more runtimes requires a change of the `deadpool` crate itself.

I almost went with the reference implementation I wrote in my `async-runtime` repository (https://github.com/bikeshedder/async-runtime) but decided against it due to the extra allocations.

I'd still like to see the timeout feature added to `async_executors` so I can use it for my future library projects. For `deadpool` I feel like the extra allocations are not needed and managing that enum is dead simple.

**Comment by najamelan** [comment]
@bikeshedder I have to apologise. I didn't come round to trying the implementation you proposed as I promised. I didn't forget and it's still on my todo list.

@qiujiangkun I'm happy to look at timers again, but lets integrate the work on glommio first ;)

**Comment by nmathewson** [comment]
I've had to do a limited version of this for our own internal use at Tor.  The code is in https://gitlab.torproject.org/tpo/core/arti/-/tree/main/tor-rtcompat ; for timing-related functionality see `SleepProvider` and `timer.rs`.  See the related `tor-rtmock` crate in the same repository for testing support; some of the design decisions there are made so that test mocking is possible.

Anyway, this isn't general-purpose, but it might have ideas or code that you could use. If so, please feel free! I hope it's helpful.

**Comment by najamelan** [comment]
@nmathewson Thanks for sharing. Cool that tor is also using rust now. I'm a daily tor user!

**Comment by najamelan** [comment]
Ok, I've got a plan. Introducing the following traits: `Timer`, `AsyncIo`, `TokioIo`, `GlommioIo`. Depending on the following features: https://github.com/najamelan/async_executors/blob/d51c1cd07cf70bfe4217b8322acd121fca0148ca/Cargo.yml#L49

It's a hefty list of features, but it's what I could come up with that in theory should work. What do you all think? Now all that is left is to implement, test and document...hurray.

**Comment by najamelan** [comment]
I just pushed an implementation for `Timer`. It doesn't have documentation yet. I will also still add an extension trait with convenience methods `fn timeout( fut: F, duration: Duration ) -> TimeoutFuture`

**Comment by qiujiangkun** [comment]
How about implementing a `SpawnBlocking` btw?

**Comment by najamelan** [comment]
The problem with spawnblocking is that our `JoinHandle` allows to cancel futures. However blocking tasks cannot be cancelled. So we would need to create a different BlockingJoinHandle type. We could do that if there is demand. Neither tokio nor async-std explain what happens when you cancel their JoinHandle when it's a blocking task. I would have to look in the code. However, tokio docs specify that a blocking task cannot be cancelled.

**Comment by qiujiangkun** [comment]
What about a YieldNow trait?

**Comment by najamelan** [comment]
Which executors support this operation? If it is only tokio, better we just add a `yield_now` method to the tokio executors.

**Comment by qiujiangkun** [comment]
Glommio, Tokio, async_std, and almost any executors support it. 
The implementation in tokio can work on any other executors, but some executors has more performant equvalents. `glommio::Task::<()>::yield_if_needed()`

**Comment by najamelan** [comment]
Timer and YieldNow have been implemented. Will still look into SpawnBlocking and a timeout future for Timer as currently it just does sleep.

**Comment by najamelan** [comment]
SpawnBlocking and Timeout future are now implement. SpawnBlocking is only available on executors that support it. Possibly with a feature "blocking" we could use the blocking crate to enable support on the single threaded executors.

I think we're getting there.

**Comment by qiujiangkun** [comment]
Note that special attention should be paid to glommio. core_affinity is derived from parent thread. If we `std::thread:spawn` in `glommio_ct`, the performance may hurt.

**Comment by najamelan** [comment]
> Note that special attention should be paid to glommio. core_affinity is derived from parent thread. If we `std::thread:spawn` in `glommio_ct`, the performance may hurt.

I think in that case it would be best to propose glommio implement a spawn_blocking function so we can just use it. I don't plan in doing manual thread management in here. There is crates like `blocking` specially for this purpose.

**Comment by qiujiangkun** [comment]
Can we use `yield_if_needed()` from glommio? I'm not sure if current `yield_now()` works in glommio
```rust
    fn yield_now() -> BoxFuture<'static, ()> {
        Box::pin(Task::<()>::yield_if_needed())
    }
```

**Comment by najamelan** [comment]
> I'm not sure if current yield_now() works in glommio

According to the integration tests it works. It's not impossible to do what you suggest, but I don't really see the point.

**Comment by qiujiangkun** [comment]
> Glommio Latency ring: Operations that are latency sensitive can be put in the latency ring. The crate has a function called yield_if_needed() that efficiently checks if there are events pending in the latency ring. Because this crate uses cooperative programming, tasks run until they either complete or decide to yield, which means they can run for a very long time before tasks that are latency sensitive have a chance to run. Every time you fire a long-running operation (usually a loop) it is good practice to check yield_if_needed() periodically (for example after x iterations of the loop). In particular, a when a new priority class is registered, one can specify if it contains latency sensitive tasks or not. And if the queue is marked as latency sensitive, the Latency enum takes a duration parameter that determines for how long other tasks can run even if there are no external events (by registering a timer with the io_uring). If no runnable tasks in the system are latency sensitive, this timer is not registered. Because io_uring allows for polling in the ring file descriptor, it is safe to park() even if work is present in the latency ring: before going to sleep, the latency ring’s file descriptor is registered with the main ring and any events it sees will also wake up the main ring.

**Comment by najamelan** [comment]
If it is a performance issue, then please provide benchmarks showing the difference.

**Comment by najamelan** [comment]
Actually, I figured a way to do it without boxing. Check the last commit on dev.

**Comment by qiujiangkun** [comment]
Is current timeout object -safe?

**Comment by najamelan** [comment]
It is, but there is a problem. `Timer` has an associated type, which means that users must specify it like:

```rs
type Exec = Box< dyn Timer< SleepFuture = Delay > + Send >;
```
This one would only work with the executors that use `futures-timer`. So that was not the intent. We will have to box here to get rid of the associated type until async in trait becomes a thing.

**Comment by najamelan** [comment]
Timer trait has been fixed. I think we can roll out a 0.4.3 soon.

**Comment by najamelan** [comment]
@bikeshedder maybe this can be closed now?

**Comment by bikeshedder** [comment]
I guess when this feature is implemented it can be closed. I just don't feel like this should be my responsibility as I'm no user of `async_executor` and therefore can't evaluate it right now. :see_no_evil:

**Comment by najamelan** [comment]
As far as I can tell it's implemented and released, but as you opened the issue I didn't want to close without asking if you feel it's solved. Given your answer, I'll close it.
